
dataset_attributes:
  image_features:
    train: /datastore/npl/ViInfographicCaps/data/swintextspotter, /datastore/npl/ViInfographicCaps/data/yolo_object
    val: /datastore/npl/ViInfographicCaps/data/swintextspotter, /datastore/npl/ViInfographicCaps/data/yolo_object
    test: /datastore/npl/ViInfographicCaps/data/swintextspotter, /datastore/npl/ViInfographicCaps/data/yolo_object
  imdb_files:
    train: /datastore/npl/ViInfographicCaps/data/imdb/train_imdb_yolo_new_no_segmented.npy
    val: /datastore/npl/ViInfographicCaps/data/imdb/val_imdb_yolo_new_no_segmented.npy
    test: /datastore/npl/ViInfographicCaps/data/imdb/test_imdb_yolo_new_no_segmented.npy

model_attributes:
  image_dir: /datastore/npl/ViInfographicCaps/data/images
  model_clip: /datastore/npl/ViInfographicCaps/model/clip-vit-large-patch14
  fasttext_bin: ./utils/fasttext/wiki.vi.bin
  pretrained: /datastore/npl/ViInfographicCaps/model/vit5-base
  model_decoder: /datastore/npl/ViInfographicCaps/model/phobert-base
  hidden_size: 768
  feature_dim: 2048 # d

  ocr:
    dim: 256
    num_ocr: 100
    spatial_circle_position:
      num_grid_patches: 11
      num_distances: 32
      num_heads: 12
    constituent_module:
      num_heads: 3
    self_attn:
      num_heads: 2
    poswise_ffn:
      ffn_dim: 512
      dropout: 0.1

  obj:
    dim: 320
    num_obj: 100
  
  mutimodal_transformer:
    num_layers: 4
    nhead: 12
    max_length: 50
    dropout: 0.1
  
  adjust_optimizer:
    lr_scale: 0.1 # scale lr for finetuning modules
optimizer_attributes:
  lr_scale: 0.1 # scale lr for finetuning modules
  params:
    eps: 1.0e-08
    lr: 1.0e-4
    weight_decay: 0.01
  type: AdamW
training_parameters:
  epochs: 26
  batch_size: 64
  early_stopping:
    patience: 5
  lr_scheduler:
    status: true
    type: "step"
    gamma : 0.1
    lr_steps:
      - 7000
    lr_ratio: 0.1
    use_warmup: True
    warmup_iterations: 1
    warmup_epochs: 5
    decay_factor: 0.3
    lr_epoch_step_size: 10
  max_iterations: 9000
  snapshot_interval: 1000
  epoch_snapshot_interval: 3
  metric_minimize: false
  seed: 2021


    